### ISSUE TITLE
Error in .check.hsmmspec(model) : No sojourn distribution specified!

### ISSUE THREAD

**Issue by hassheh** [jaredo/mhsmm#10]
This is not really an issue but I need help with this. maybe someone could help me. I have used this package for my own univariate time series data. I don't know what I'm missing which is causing it to throw this error
> Error in .check.hsmmspec(model) : No sojourn distribution specified!

Here is my code. I have tried using the both sojourn given in the reference paper for testing but does not seem to work.
`J<-3`
`initial <- rep(1/J,J)`
`P <- matrix(c(.5, .5, .5, .5, .5, .5, .5, .5, .5), nrow =J)`
`b <- list(mu = c(2.9, 4.9, 5.6), sigma = c(1 ,1 ,1))`
`d <- cbind(dunif(1:50, 0, 30), dunif(1:50, 30, 40), dunif(1:50, 35, 40))`
`sojourn = list(d = d, type = "nonparametric")`
`sojourn = list(lambda = c(9, 25, 40), shift = c(5, 95, 45), type = "poisson")`
`model <- hmmspec(init=initial, trans=P, parms.emission=b, sojourn, dens.emission=dnorm.hsmm)`

`N <- as.numeric(1)`
`train <- list(x = GL_up$Glucose_values, N = N)`
`class(train) <- "hsmm.data"`

`h1 <- hsmmfit(train, model, mstep = mstep.norm, maxit=500, graphical = TRUE)`

**Comment by vrodriguezf** [comment]
Shouldn't be `hsmmspec` instead of `hmmspec`?

**Comment by hassheh** [comment]
No, hsmmfit should be hmmfit. It's always something small. Thanks.

**Comment by vrodriguezf** [comment]
It's not about the size of the model, it's about the parameters of the function. The headers of `hmmspec` and `hsmmspec` are different, since HMMs do not have sojourn distributions.
