### ISSUE TITLE
loglikelihood

### ISSUE THREAD

**Issue by XinruLiu** [jaredo/mhsmm#11]
Can I know how you calculate the log-likelihood value??

**Comment by jaredo** [comment]
You can extract the log-likelihood (from each iteration of EM) from an hmm/hsmm via `object$loglik`. See `help(hmmfit)` for an example.

**Comment by XinruLiu** [comment]
Yes, I know how to get the value from object$loglik. I just wonder did you compute the value just through taking the log of the P(O|parameter) or did you do the extra step? I calculated the log-likelihood from P(O|parameter) by myself but it is different from what I got from your loglik. Thank you.

**Comment by jaredo** [comment]
It should just be the log-likelihood, P(O|parameters), which is calculated using the Forward step of the EM routine as described in [Rabiner] (http://www.ee.iisc.ac.in/new/people/faculty/prasantg/downloads/hmm_Rabiner_Tutorial.pdf).

I have never validated this against other implementations though and there is a scaling trick involved. How different is your value and how did you calculate it?

**Comment by XinruLiu** [comment]
I also use the forward algorithm, given by P(O|parameters)=alpha_final(1) + alpha_final(2)...+alpha_final(N) and then take the log.
I used a simple example below
```
init0 <- rep(1/3,3)
a <- matrix(c(0.5, 0.25, 0.25, 0.3, 0.4, 0.3, 0.25, 0.25, 0.5),byrow = T, nrow = 3)
b <- list(mu=c(0.87, 0.14, 0.39), sigma=c(0.9, 0.9, 0.9))
hmm.startval<- hmmspec(init = init0, trans = a, parms.emission = b, dens.emission = dnorm.hsmm)
train <- list(x=t(cbind(0.88, 0.13, 0.38)), N=3)
class(train) <- "hsmm.data"
h1<-hmmfit(train, hmm.startval, mstep=mstep.norm, maxit = 1)
```
The log likelihood for the first iteration I got -6.36241 from my side and -2.90377 from your side. Second iteration I got -5.422206 from my side and -0.8610614 from your side.

**Comment by jaredo** [comment]
I don't have your code so it is hard to say whether this is a bug in hsmm or not.

What scaling routine are you using to keep the alphas within machine precision?  Are you using the one described in Rabiner?   See equations 90 through 103:

http://www.robots.ox.ac.uk:5000/~vgg/rg/papers/hmm.pdf

**Comment by XinruLiu** [comment]
Okay, I will have a look. Also, I have another question that have been bothering me for a long time if you don't mind answering. I keep getting two error message "Error: at least one state has an expected number of occurrences equal to 0.\n This may be caused by bad starting parameters are insufficient sample size" and "Some values have emission pdf=0 for all states!  Check your model parameters". I know it is hard for you to answer this without an example. But do you have any insight into what may cause these two error messages?

**Comment by jaredo** [comment]
That error message indicates some sort of convergence issue.

If you take your above toy example, there are 12 parameters and only N=3 observations, you can not estimate so many parameters with so few observations.

Another cause can be the starting values for an emission distribution being very unlikely to generate any of the emitted observations. The density may be so low that it is beyond machine precision. 

eg.

```
> dnorm(0,mean=100)==0
[1] TRUE
```

**Comment by XinruLiu** [comment]
That makes sense. Thank you very much.

**Comment by XinruLiu** [comment]
Hi, sorry to bother you again. I looked up the equations in the Rabiner's paper and they make sense to me. But what I am still confused with is sometimes likelihood computed from hsmm is positive and it becomes larger when the input data length increases. From the definition of the log(P(O|parameter)), since P(O|parameter) is always<0, log(something <0) should be always negative. Did you do anything other than the scaling from Rabiner's paper? Thank you!

**Comment by vrodriguezf** [comment]
I don't know what's the exact implementation in this package, but there are other implementations such as the function score in the [hmmlearn](https://hmmlearn.readthedocs.io/en/latest/) package that can return positive values. Actually, here's a post talking about positive log likelihoods:
https://blog.stata.com/2011/02/16/positive-log-likelihood-values-happen/
