### ISSUE TITLE
Non-parametric Sojourn distribution is not updated in hsmmfit

### ISSUE THREAD

**Issue by lordbitin** [jaredo/mhsmm#2]
Hi,

I'm having troubles when fitting some HSMMs with non-parametric sojourn distributions using the function `hsmmfit()`. When I set the `graphical=TRUE`, I can see how the sojourn distributions are updated for each iteration in the function. However, when the process ends, the value of the MxJ sojourn matrix `model$sojourn` is the same as in the initial model.

Is it a bug in the package, or may be am I doing something wrong? Executing the code snippets from the mhsmm tutorial (http://www.jstatsoft.org/v39/i04/paper), the problem remains...

Thanks in advance!
Víctor

**Comment by jaredo** [comment]
This is fixed in 0.4.15. The bug did not actually affect the model fitting or downstream prediction since `model$sojourn` was not actually used in those process.

Apologies for taking 18 months!
