### ISSUE TITLE
Unnecessary warning message

### ISSUE THREAD

**Issue by brendanrock** [jaredo/mhsmm#5]
In the documentation it notes that the input to predict must be an object (prediction model) and a data frame or vector to predict on. Although prediction works on a vector, the warning "x is a primitive vector.  Assuming single sequence." is outputted. This is an issue when predicting on a large amount of data as the console is flooded with output. Instead the warning should only be issued if the length of vector is less than 1.

**Comment by jaredo** [comment]
Hi Brendan,
 
Thanks for your interest in the package. The warning is there to protect against users accidentally feeding the tool multiple independent sequences (and having them treated as a single sequence). You can remove it via putting your emitted variable vector in a list along with its length.

For example

```
library(mhsmm)

J<-3
initial <- rep(1/J,J)
P <- matrix(c(.8,.5,.1,0.05,.2,.5,.15,.3,.4),nrow=J)
b <- list(mu=c(-3,0,2),sigma=c(2,1,.5))
model <- hmmspec(init=initial, trans=P, parms.emission=b,dens.emission=dnorm.hsmm)
model

train <- simulate(model, nsim=300, seed=1234, rand.emis=rnorm.hsmm)

observed <- train$x
y <- predict(model,observed) #warning
y <- predict(model,list(x=observed,N=length(observed))) #no warning
```

The documentation could have been better here and I will try to improve it when I find time.

I hope that helps.

best,

Jared

**Comment by jaredo** [comment]
Yes - the documentation is wrong! It should say list, not data.frame. You can take a look at the output from `simulate.hmmspec` to see the structure of said list.
